# Generated by Django 4.2.5 on 2023-12-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
